

export const MOODS = [
  { value: 1, label: 'Awful', emoji: '😫', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500/20' },
  { value: 2, label: 'Bad', emoji: '😔', color: 'text-orange-400', bg: 'bg-orange-500/10', border: 'border-orange-500/20' },
  { value: 3, label: 'Okay', emoji: '😐', color: 'text-gray-400', bg: 'bg-gray-500/10', border: 'border-gray-500/20' },
  { value: 4, label: 'Good', emoji: '🙂', color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
  { value: 5, label: 'Great', emoji: '🤩', color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/20' },
];

export const ACTIVITIES = [
  'Work', 'Exercise', 'Family', 'Date', 'Gaming', 'Reading', 'Party', 'Relaxing', 'Cleaning'
];

export const SYMPTOMS = [
  'Anxiety', 'Headache', 'Fatigue', 'Insomnia', 'Stress', 'Nausea'
];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    diary: 'My Diary',
    stats: 'Insights',
    settings: 'Settings',
    hello: 'Hello,',
    readyTrack: 'Ready to track your journey today?',
    noEntries: 'No entries yet',
    waitingStory: 'Your journal is waiting for your first story.',
    startNow: 'Start Now',
    lastMood: 'Last Mood',
    entries: 'Entries',
    recentActivity: 'Recent Activity',
    private: 'Private',
    shared: 'Shared',
    quickActions: 'Quick Actions',
    logMood: 'Log Mood',
    voiceLog: 'Voice Log',
    writeDiary: 'Write Diary',
    diaryTitle: 'My Diary',
    diarySubtitle: 'A space for your thoughts and stories.',
    writeNew: '+ Write New',
    emptyBook: 'Your book is empty.',
    insights: 'Insights',
    noData: 'No data available yet. Log your first mood!',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    moodFlow: 'Mood Flow',
    energyLevels: 'Energy Levels',
    recent: 'Recent',
    days7: '7 Days',
    days30: '30 Days',
    accountSettings: 'Account & Settings',
    language: 'Language',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account Permanently',
    switchRole: 'Switch Role',
    tabMood: '📊 Mood',
    tabDiary: '📖 Diary',
    tabVoice: '🎙️ Voice AI',
    listening: 'I am listening...',
    voicePrompt: 'Tell me about your day or how you feel.\nThe AI will detect your mood and write in your diary.',
    howAreYou: 'How are you feeling?',
    energy: 'Energy Level',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Dear Diary...',
    placeholderDiary: 'Start writing or use voice...',
    placeholderMood: 'Anything to add?',
    cancel: 'Cancel',
    save: 'Save Entry',
    login: 'Login',
    createAccount: 'Create Account',
    backToLogin: 'Back to Login',
    orEmail: 'Or via email',
    continueGoogle: 'Continue with Google',
    standardUser: 'Standard User',
    patientMode: 'Patient Mode',
    professional: 'Professional',
    stdDesc: 'Personal journaling. Private analytics.',
    patDesc: 'Share specific logs with your therapist.',
    docDesc: 'For therapists to view patient data.',
    back: 'Back',
    docPortal: 'Therapist Portal',
    yourPatients: 'Your Patients',
    connectPatient: 'Connect Patient',
    enterPatientEmail: 'Enter patient email',
    connect: 'Connect',
    noPatients: 'No patients connected.',
    selectPatient: 'Select a patient to view records.',
    clinicalNotes: 'Clinical Observations',
    addNote: 'Add Note',
    saveNote: 'Save Note',
    patientNotFound: 'Patient not found. Created a demo patient.',
    alreadyConnected: 'Patient already in your list.',
    visibleEntries: 'Visible Entries',
    avgMood: 'Avg Mood',
    avgEnergy: 'Avg Energy',
    moodProgression: 'Mood Progression',
    privateNotes: 'Private Notes',
    sharedNotes: 'Message to Patient',
    sharedWithPatient: 'Shared with Patient',
    doctorMessage: 'Message from your Doctor',
    micOn: 'Listening...',
    micOff: 'Record Voice Note',
    selectDate: 'Select Date',
    selectMonth: 'Select Month',
    viewMode: 'View Mode',
    viewDay: 'Specific Day',
    viewMonth: 'Specific Month',
    reply: 'Reply',
    writeReply: 'Write a reply...',
    sendReply: 'Send',
    userIsStandard: 'User found, but they are a Standard User. They must upgrade to Patient Mode in their settings.',
    upgradeToPatient: 'Enable Patient Features (Connect with Doctor)',
    upgradeSuccess: 'Account upgraded to Patient Mode. You can now connect with a doctor.',
    recentNotifications: 'Recent Notifications',
    sentReply: 'replied to a note',
    viewConversation: 'View Conversation',
    deleteConfirm: 'Are you sure? This cannot be undone.'
  },
  pt: {
    home: 'Início',
    diary: 'Diário',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Olá,',
    readyTrack: 'Pronto para registrar sua jornada hoje?',
    noEntries: 'Nenhum registro ainda',
    waitingStory: 'Seu diário está esperando sua primeira história.',
    startNow: 'Começar Agora',
    lastMood: 'Último Humor',
    entries: 'Registros',
    recentActivity: 'Atividade Recente',
    private: 'Privado',
    shared: 'Compartilhado',
    quickActions: 'Ações Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Voz',
    writeDiary: 'Escrever Diário',
    diaryTitle: 'Meu Diário',
    diarySubtitle: 'Um espaço para seus pensamentos e histórias.',
    writeNew: '+ Escrever',
    emptyBook: 'Seu livro está vazio.',
    insights: 'Estatísticas',
    noData: 'Sem dados ainda. Registre seu primeiro humor!',
    daily: 'Diário',
    weekly: 'Semanal',
    monthly: 'Mensal',
    moodFlow: 'Fluxo de Humor',
    energyLevels: 'Níveis de Energia',
    recent: 'Recente',
    days7: '7 Dias',
    days30: '30 Dias',
    accountSettings: 'Conta e Configurações',
    language: 'Idioma',
    name: 'Nome',
    email: 'E-mail',
    role: 'Perfil',
    signOut: 'Sair',
    deleteAccount: 'Excluir Conta Permanentemente',
    switchRole: 'Trocar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diário',
    tabVoice: '🎙️ Voz IA',
    listening: 'Estou ouvindo...',
    voicePrompt: 'Conte sobre seu dia ou como se sente.\nA IA detectará seu humor e escreverá no diário.',
    howAreYou: 'Como você está se sentindo?',
    energy: 'Nível de Energia',
    tags: 'Tags',
    notesTitle: '📝 Notas',
    diaryPromptTitle: 'Querido Diário...',
    placeholderDiary: 'Comece a escrever ou use a voz...',
    placeholderMood: 'Algo a acrescentar?',
    cancel: 'Cancelar',
    save: 'Salvar Registro',
    login: 'Entrar',
    createAccount: 'Criar Conta',
    backToLogin: 'Voltar para Login',
    orEmail: 'Ou via e-mail',
    continueGoogle: 'Continuar com Google',
    standardUser: 'Usuário Comum',
    patientMode: 'Paciente',
    professional: 'Profissional',
    stdDesc: 'Diário pessoal. Análises privadas.',
    patDesc: 'Compartilhe registros específicos com seu terapeuta.',
    docDesc: 'Para terapeutas visualizarem dados de pacientes.',
    back: 'Voltar',
    docPortal: 'Portal do Terapeuta',
    yourPatients: 'Seus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Digite o e-mail do paciente',
    connect: 'Conectar',
    noPatients: 'Nenhum paciente conectado.',
    selectPatient: 'Selecione um paciente para ver os registros.',
    clinicalNotes: 'Observações Clínicas',
    addNote: 'Adicionar Nota',
    saveNote: 'Salvar Nota',
    patientNotFound: 'Paciente não encontrado. Criamos um usuário de teste.',
    alreadyConnected: 'Paciente já está na sua lista.',
    visibleEntries: 'Registros Visíveis',
    avgMood: 'Média Humor',
    avgEnergy: 'Média Energia',
    moodProgression: 'Evolução do Humor',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensagem ao Paciente',
    sharedWithPatient: 'Compartilhado com Paciente',
    doctorMessage: 'Mensagem do seu Médico',
    micOn: 'Ouvindo...',
    micOff: 'Gravar Nota de Voz',
    selectDate: 'Selecionar Data',
    selectMonth: 'Selecionar Mês',
    viewMode: 'Modo de Visualização',
    viewDay: 'Dia Específico',
    viewMonth: 'Mês Específico',
    reply: 'Responder',
    writeReply: 'Escreva uma resposta...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuário encontrado, mas é Comum. Ele precisa ativar o modo Paciente nas configurações dele.',
    upgradeToPatient: 'Ativar Modo Paciente (Conectar com Médico)',
    upgradeSuccess: 'Conta atualizada para Paciente. Agora você pode conectar com um médico.',
    recentNotifications: 'Notificações Recentes',
    sentReply: 'respondeu a uma nota',
    viewConversation: 'Ver Conversa',
    deleteConfirm: 'Tem certeza? Isso não pode ser desfeito.'
  },
  es: {
    home: 'Inicio',
    diary: 'Diario',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Hola,',
    readyTrack: '¿Listo para registrar tu día?',
    noEntries: 'Sin registros aún',
    waitingStory: 'Tu diario espera tu primera historia.',
    startNow: 'Empezar Ahora',
    lastMood: 'Último Humor',
    entries: 'Entradas',
    recentActivity: 'Actividad Reciente',
    private: 'Privado',
    shared: 'Compartido',
    quickActions: 'Acciones Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Voz',
    writeDiary: 'Escribir Diario',
    diaryTitle: 'Mi Diario',
    diarySubtitle: 'Un espacio para tus pensamientos e historias.',
    writeNew: '+ Escribir',
    emptyBook: 'Tu libro está vacío.',
    insights: 'Estadísticas',
    noData: 'Sin datos aún. ¡Registra tu primer humor!',
    daily: 'Diario',
    weekly: 'Semanal',
    monthly: 'Mensual',
    moodFlow: 'Flujo de Humor',
    energyLevels: 'Niveles de Energía',
    recent: 'Reciente',
    days7: '7 Días',
    days30: '30 Días',
    accountSettings: 'Cuenta y Configuración',
    language: 'Idioma',
    name: 'Nombre',
    email: 'Correo',
    role: 'Perfil',
    signOut: 'Cerrar Sesión',
    deleteAccount: 'Eliminar Cuenta Permanentemente',
    switchRole: 'Cambiar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diario',
    tabVoice: '🎙️ Voz IA',
    listening: 'Te escucho...',
    voicePrompt: 'Cuéntame sobre tu día o cómo te sientes.\nLa IA detectará tu humor y escribirá en el diario.',
    howAreYou: '¿Cómo te sientes?',
    energy: 'Nivel de Energía',
    tags: 'Etiquetas',
    notesTitle: '📝 Notas',
    diaryPromptTitle: '📖 Querido Diario...',
    placeholderDiary: 'Empieza a escribir o usa la voz...',
    placeholderMood: '¿Algo que añadir?',
    cancel: 'Cancelar',
    save: 'Guardar',
    login: 'Entrar',
    createAccount: 'Crear Cuenta',
    backToLogin: 'Volver al Login',
    orEmail: 'O vía correo',
    continueGoogle: 'Continuar con Google',
    standardUser: 'Usuario Estándar',
    patientMode: 'Paciente',
    professional: 'Profesional',
    stdDesc: 'Diario personal. Análisis privados.',
    patDesc: 'Comparte registros específicos con tu terapeuta.',
    docDesc: 'Para terapeutas ver datos de pacientes.',
    back: 'Volver',
    docPortal: 'Portal del Terapeuta',
    yourPatients: 'Tus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Ingresa correo del paciente',
    connect: 'Conectar',
    noPatients: 'Ningún paciente conectado.',
    selectPatient: 'Selecciona un paciente para ver registros.',
    clinicalNotes: 'Observaciones Clínicas',
    addNote: 'Añadir Nota',
    saveNote: 'Guardar Nota',
    patientNotFound: 'Paciente no encontrado. Creamos usuario de prueba.',
    alreadyConnected: 'Paciente ya está en tu lista.',
    visibleEntries: 'Entradas Visibles',
    avgMood: 'Promedio Humor',
    avgEnergy: 'Promedio Energía',
    moodProgression: 'Evolución del Humor',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensaje al Paciente',
    sharedWithPatient: 'Compartido con el Paciente',
    doctorMessage: 'Mensaje de tu Médico',
    micOn: 'Escuchando...',
    micOff: 'Grabar Nota de Voz',
    selectDate: 'Seleccionar Fecha',
    selectMonth: 'Seleccionar Mes',
    viewMode: 'Modo de Visualización',
    viewDay: 'Día Específico',
    viewMonth: 'Mes Específico',
    reply: 'Responder',
    writeReply: 'Escribir respuesta...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuario encontrado, pero es Estándar. Debe actualizar a modo Paciente en sus ajustes.',
    upgradeToPatient: 'Activar Modo Paciente',
    upgradeSuccess: 'Cuenta actualizada a Paciente.',
    recentNotifications: 'Notificaciones Recientes',
    sentReply: 'respondió a una nota',
    viewConversation: 'Ver Conversación',
    deleteConfirm: '¿Seguro? No se puede deshacer.'
  },
  fr: {
    home: 'Accueil',
    diary: 'Journal',
    stats: 'Graphiques',
    settings: 'Réglages',
    hello: 'Bonjour,',
    readyTrack: 'Prêt à suivre votre journée ?',
    noEntries: 'Aucune entrée pour le moment',
    waitingStory: 'Votre journal attend votre première histoire.',
    startNow: 'Commencer',
    lastMood: 'Dernière humeur',
    entries: 'Entrées',
    recentActivity: 'Activité Récente',
    private: 'Privé',
    shared: 'Partagé',
    quickActions: 'Actions Rapides',
    logMood: 'Enregistrer Humeur',
    voiceLog: 'Voix',
    writeDiary: 'Écrire Journal',
    diaryTitle: 'Mon Journal',
    diarySubtitle: 'Un espace pour vos pensées et histoires.',
    writeNew: '+ Écrire',
    emptyBook: 'Votre livre est vide.',
    insights: 'Statistiques',
    noData: 'Pas de données. Enregistrez votre première humeur !',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    moodFlow: 'Flux d\'Humeur',
    energyLevels: 'Niveaux d\'Énergie',
    recent: 'Récent',
    days7: '7 Jours',
    days30: '30 Jours',
    accountSettings: 'Compte et Paramètres',
    language: 'Langue',
    name: 'Nom',
    email: 'E-mail',
    role: 'Rôle',
    signOut: 'Déconnexion',
    deleteAccount: 'Supprimer le compte définitivement',
    switchRole: 'Changer de Rôle',
    tabMood: '📊 Humeur',
    tabDiary: '📖 Journal',
    tabVoice: '🎙️ Voix IA',
    listening: 'Je vous écoute...',
    voicePrompt: 'Parlez de votre journée ou de vos sentiments.\nL\'IA détectera votre humeur et écrira dans le journal.',
    howAreYou: 'Comment vous sentez-vous ?',
    energy: 'Niveau d\'Énergie',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Cher Journal...',
    placeholderDiary: 'Commencez à écrire ou utilisez la voix...',
    placeholderMood: 'Quelque chose à ajouter ?',
    cancel: 'Annuler',
    save: 'Enregistrer',
    login: 'Connexion',
    createAccount: 'Créer Compte',
    backToLogin: 'Retour Connexion',
    orEmail: 'Ou via e-mail',
    continueGoogle: 'Continuer avec Google',
    standardUser: 'Utilisateur Standard',
    patientMode: 'Patient',
    professional: 'Professionnel',
    stdDesc: 'Journal personnel. Analyses privées.',
    patDesc: 'Partagez des journaux spécifiques avec votre thérapeute.',
    docDesc: 'Pour les thérapeutes visualizant les données.',
    back: 'Retour',
    docPortal: 'Portail Thérapeute',
    yourPatients: 'Vos Patients',
    connectPatient: 'Connecter Patient',
    enterPatientEmail: 'Entrez l\'email du patient',
    connect: 'Connecter',
    noPatients: 'Aucun patient connecté.',
    selectPatient: 'Sélectionnez un patient pour voir les dossiers.',
    clinicalNotes: 'Observations Cliniques',
    addNote: 'Ajouter Note',
    saveNote: 'Enregistrer Note',
    patientNotFound: 'Patient introuvable. Utilisateur test créé.',
    alreadyConnected: 'Patient déjà dans votre liste.',
    visibleEntries: 'Entrées Visibles',
    avgMood: 'Moyenne Humeur',
    avgEnergy: 'Moyenne Énergie',
    moodProgression: 'Évolution de l\'Humeur',
    privateNotes: 'Notes Privées',
    sharedNotes: 'Message au Patient',
    sharedWithPatient: 'Partagé avec le Patient',
    doctorMessage: 'Message de votre Docteur',
    micOn: 'Écoute...',
    micOff: 'Enregistrer Note Vocale',
    selectDate: 'Sélectionner Date',
    selectMonth: 'Sélectionner Mois',
    viewMode: 'Mode d\'Affichage',
    viewDay: 'Jour Spécifique',
    viewMonth: 'Mois Spécifique',
    reply: 'Répondre',
    writeReply: 'Écrire une réponse...',
    sendReply: 'Envoyer',
    userIsStandard: 'Utilisateur trouvé, mais Standard. Doit passer en mode Patient.',
    upgradeToPatient: 'Activer Mode Patient',
    upgradeSuccess: 'Compte mis à jour en mode Patient.',
    recentNotifications: 'Notifications Récentes',
    sentReply: 'a répondu',
    viewConversation: 'Voir Conversation',
    deleteConfirm: 'Êtes-vous sûr ?'
  }
};