
export const MOODS = [
  { value: 1, label: 'Awful', emoji: '😫', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500/20' },
  { value: 2, label: 'Bad', emoji: '😔', color: 'text-orange-400', bg: 'bg-orange-500/10', border: 'border-orange-500/20' },
  { value: 3, label: 'Okay', emoji: '😐', color: 'text-gray-400', bg: 'bg-gray-500/10', border: 'border-gray-500/20' },
  { value: 4, label: 'Good', emoji: '🙂', color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
  { value: 5, label: 'Great', emoji: '🤩', color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/20' },
];

export const ACTIVITIES = [
  'Work', 'Exercise', 'Family', 'Date', 'Gaming', 'Reading', 'Party', 'Relaxing', 'Cleaning'
];

export const SYMPTOMS = [
  'Anxiety', 'Headache', 'Fatigue', 'Insomnia', 'Stress', 'Nausea'
];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    diary: 'My Diary',
    stats: 'Insights',
    settings: 'Settings',
    hello: 'Hello,',
    readyTrack: 'Ready to track your journey today?',
    clinicalSecurity: 'Your emotional journey with clinical security',
    noEntries: 'No entries yet',
    waitingStory: 'Your journal is waiting for your first story.',
    startNow: 'Start Now',
    lastMood: 'Last Mood',
    entries: 'Entries',
    connectedDoctors: 'Connected Doctors',
    recentActivity: 'Recent Activity',
    securityTransparency: 'Security & Transparency',
    dataAccessHistory: 'Data Access History',
    accessedBy: 'Accessed by',
    at: 'at',
    clinicalInsights: 'Clinical Insights',
    generateClinicalSummary: 'Generate Clinical Summary',
    executiveSummary: 'Executive Summary',
    identifiedPatterns: 'Identified Patterns',
    clinicalRecommendations: 'Clinical Recommendations',
    newClinic: 'New Unit / Clinic',
    yourClinics: 'Your Units',
    createUnit: 'Create Unit',
    downloadDataLGPD: 'Download My Data (GDPR / Portability)',
    printReport: 'Print Clinical Report',
    exportExcel: 'Export Excel',
    resolve: 'Resolve',
    hide: 'Hide',
    consent: 'Consent Management',
    patients: 'Patients',
    riskLevel: 'Risk Level',
    riskLevels: {
      low: 'Stable',
      medium: 'Moderate Risk',
      high: 'High Risk'
    },
    shared: 'Shared',
    quickActions: 'Quick Actions',
    logMood: 'Log Mood',
    voiceLog: 'Voice Log',
    writeDiary: 'Write Diary',
    diaryTitle: 'My Diary',
    diarySubtitle: 'A space for your thoughts and stories.',
    writeNew: '+ Write New',
    emptyBook: 'Your book is empty.',
    insights: 'Insights',
    noData: 'No data available yet. Log your first mood!',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    moodFlow: 'Mood Flow',
    energyLevels: 'Energy Levels',
    recent: 'Recent',
    days7: '7 Days',
    days30: '30 Days',
    accountSettings: 'Account & Settings',
    language: 'Language',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account Permanently',
    switchRole: 'Switch Role',
    tabMood: '📊 Mood',
    tabDiary: '📖 Diary',
    tabVoice: '🎙️ Voice Recording',
    listening: 'I am listening...',
    voicePrompt: 'Tell me about your day or how you feel.\nThe system will detect your mood and write in your diary.',
    howAreYou: 'How are you feeling?',
    energy: 'Energy Level',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Dear Diary...',
    placeholderDiary: 'Start writing or use voice...',
    placeholderMood: 'Anything to add?',
    cancel: 'Cancel',
    save: 'Save Entry',
    login: 'Login',
    createAccount: 'Create Account',
    backToLogin: 'Back to Login',
    orEmail: 'Or via email',
    standardUser: 'Standard User',
    patientMode: 'Patient',
    professional: 'Professional',
    stdDesc: 'Personal journaling. Private analytics.',
    patDesc: 'Share specific logs with your therapist.',
    docDesc: 'For therapists to view patient data.',
    roleConfirmed: 'Role confirmed.',
    back: 'Back',
    docPortal: 'Therapist Portal',
    yourPatients: 'Your Patients',
    connectPatient: 'Connect Patient',
    enterPatientEmail: 'Enter patient email',
    connect: 'Connect',
    noPatients: 'No patients connected.',
    selectPatient: 'Select a patient to view records.',
    clinicalNotes: 'Clinical Observations',
    addNote: 'Add Note',
    saveNote: 'Save Note',
    patientNotFound: 'Patient not found. Created a demo patient.',
    alreadyConnected: 'Patient already in your list.',
    visibleEntries: 'Visible Entries',
    avgMood: 'Avg Mood',
    avgEnergy: 'Avg Energy',
    moodProgression: 'Mood Progression',
    privateNotes: 'Private Notes',
    sharedNotes: 'Message to Patient',
    sharedWithPatient: 'Shared with Patient',
    doctorMessage: 'Message from your Doctor',
    micOn: 'Listening...',
    micOff: 'Record Voice Note',
    selectDate: 'Select Date',
    selectMonth: 'Select Month',
    viewMode: 'View Mode',
    viewDay: 'Day',
    viewMonth: 'Month',
    reply: 'Reply',
    writeReply: 'Write a reply...',
    sendReply: 'Send',
    userIsStandard: 'User found, but they are a Standard User. They must upgrade to Patient Mode in their settings.',
    upgradeToPatient: 'Enable Patient Features (Connect with Doctor)',
    upgradeSuccess: 'Account upgraded to Patient Mode. You can now connect with a doctor.',
    recentNotifications: 'Recent Notifications',
    sentReply: 'replied to a note',
    viewConversation: 'View Conversation',
    deleteConfirm: 'Are you sure? This cannot be undone.',
    confirmDisconnect: 'Are you sure you want to revoke this professional\'s access?',
    disconnectSuccess: 'Access revoked successfully.',
    summaryResult: 'Clinical Summary',
    summaryError: 'Failed to generate summary. Please try again.',
    consentManagement: 'Consent Management',
    moodEvolution: 'Mood Evolution',
    riskScore: 'Stability Score',
    requestAnalysis: 'Run Evolution Analysis',
    evolutionSummary: 'Evolution Summary',
    pointsOfAttention: 'Points of Attention',
    periodAnalysis: 'Period Situation'
  },
  pt: {
    home: 'Início',
    diary: 'Diário',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Olá,',
    readyTrack: 'Pronto para registrar sua jornada hoje?',
    clinicalSecurity: 'Sua jornada emocional com segurança clínica',
    noEntries: 'Nenhum registro ainda',
    waitingStory: 'Seu diário está esperando sua primeira história.',
    startNow: 'Começar Agora',
    lastMood: 'Último Humor',
    entries: 'Registros',
    connectedDoctors: 'Médicos Conectados',
    recentActivity: 'Atividade Recente',
    securityTransparency: 'Segurança & Transparência',
    dataAccessHistory: 'Histórico de Acesso aos Dados',
    accessedBy: 'Acessado por',
    at: 'em',
    clinicalInsights: 'Análises Avançadas',
    generateClinicalSummary: 'Gerar Sumário Clínico',
    executiveSummary: 'Resumo Executivo',
    identifiedPatterns: 'Padrões Identificados',
    clinicalRecommendations: 'Recomendações Clínicas',
    newClinic: 'Nova Unidade / Clínica',
    yourClinics: 'Suas Unidades',
    createUnit: 'Criar Unidade',
    downloadDataLGPD: 'Baixar meus dados (LGPD / Portability)',
    printReport: 'Imprimir Relatório Clínico',
    exportExcel: 'Exportar Excel',
    resolve: 'Resolver',
    hide: 'Ocultar',
    consent: 'Gestão de Consentimento',
    patients: 'Pacientes',
    riskLevel: 'Nível de Risco',
    riskLevels: {
      low: 'Estável',
      medium: 'Risco Moderado',
      high: 'Alto Risco'
    },
    private: 'Privado',
    shared: 'Compartilhado',
    quickActions: 'Ações Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Registro por Voz',
    writeDiary: 'Escrever Diário',
    diaryTitle: 'Meu Diário',
    diarySubtitle: 'Um espaço para seus pensamentos e histórias.',
    writeNew: '+ Escrever',
    emptyBook: 'Seu livro está vazio.',
    insights: 'Estatísticas',
    noData: 'Sem dados ainda. Registre seu primeiro humor!',
    daily: 'Diário',
    weekly: 'Semanal',
    monthly: 'Mensal',
    moodFlow: 'Fluxo de Humor',
    energyLevels: 'Níveis de Energia',
    recent: 'Recente',
    days7: '7 Dias',
    days30: '30 Dias',
    accountSettings: 'Conta e Configurações',
    language: 'Idioma',
    name: 'Nome',
    email: 'E-mail',
    role: 'Perfil',
    signOut: 'Sair',
    deleteAccount: 'Excluir Conta Permanentemente',
    switchRole: 'Trocar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diário',
    tabVoice: '🎙️ Registro por Voz',
    listening: 'Estou ouvindo...',
    voicePrompt: 'Conte sobre seu dia ou como se sente.\nO sistema processará seu humor e escreverá no diário.',
    howAreYou: 'Como você está se sentindo?',
    energy: 'Nível de Energia',
    tags: 'Tags',
    notesTitle: '📝 Notas',
    diaryPromptTitle: 'Querido Diário...',
    placeholderDiary: 'Comece a escrever ou use a voz...',
    placeholderMood: 'Algo a acrescentar?',
    cancel: 'Cancelar',
    save: 'Salvar Registro',
    login: 'Entrar',
    createAccount: 'Criar Conta',
    backToLogin: 'Voltar para Login',
    patientMode: 'Paciente',
    professional: 'Profissional',
    patDesc: 'Compartilhe registros específicos com seu terapeuta.',
    docDesc: 'Para terapeutas visualizarem dados de pacientes.',
    docPortal: 'Portal do Terapeuta',
    yourPatients: 'Seus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Digite o e-mail do paciente',
    connect: 'Conectar',
    noPatients: 'Nenhum paciente conectado.',
    selectPatient: 'Selecione um paciente para ver os registros.',
    clinicalNotes: 'Observações Clínicas',
    addNote: 'Adicionar Nota',
    saveNote: 'Salvar Nota',
    patientNotFound: 'Paciente não encontrado. Criamos um usuário de teste.',
    alreadyConnected: 'Paciente já está na sua lista.',
    visibleEntries: 'Registros Visíveis',
    avgMood: 'Média Humor',
    avgEnergy: 'Média Energia',
    moodProgression: 'Evolução do Humor',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensagem ao Paciente',
    sharedWithPatient: 'Compartilhado com Paciente',
    doctorMessage: 'Mensagem do seu Médico',
    micOn: 'Ouvindo...',
    micOff: 'Gravar Nota de Voz',
    selectDate: 'Selecionar Data',
    selectMonth: 'Selecionar Mês',
    viewMode: 'Modo de Visualização',
    viewDay: 'Dia',
    viewMonth: 'Mês',
    reply: 'Responder',
    writeReply: 'Escreva uma resposta...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuário encontrado, mas é Comum. Ele precisa ativar o modo Paciente nas configurações dele.',
    upgradeToPatient: 'Ativar Modo Paciente (Conectar com Médico)',
    upgradeSuccess: 'Conta atualizada para Paciente. Agora você pode conectar com um médico.',
    recentNotifications: 'Notificações Recentes',
    sentReply: 'respondeu uma anotação',
    viewConversation: 'Ver Conversa',
    deleteConfirm: 'Tem certeza? Esta ação não pode ser desfeita.',
    confirmDisconnect: 'Tem certeza que deseja revogar o acesso deste profissional?',
    disconnectSuccess: 'Acesso revogado com sucesso.',
    summaryResult: 'Resumo Clínico',
    summaryError: 'Falha ao gerar resumo. Tente novamente.',
    consentManagement: 'Gestão de Consentimento',
    moodEvolution: 'Análise de Evolução',
    riskScore: 'Score de Estabilidade',
    requestAnalysis: 'Analisar Evolução do Período',
    evolutionSummary: 'Sumário de Evolução',
    pointsOfAttention: 'Pontos de Atenção',
    periodAnalysis: 'Situação do Período'
  },
  es: {
    home: 'Inicio',
    diary: 'Diario',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Hola,',
    readyTrack: '¿Listo para registrar tu día?',
    clinicalSecurity: 'Tu viaje con seguridad clínica',
    noEntries: 'Sin registros aún',
    waitingStory: 'Tu diario espera tu primera historia.',
    startNow: 'Empezar Ahora',
    lastMood: 'Último Humor',
    entries: 'Registros',
    connectedDoctors: 'Médicos Conectados',
    recentActivity: 'Actividad Reciente',
    securityTransparency: 'Seguridad y Transparencia',
    dataAccessHistory: 'Historial de Acceso',
    accessedBy: 'Accedido por',
    at: 'en',
    clinicalInsights: 'Análisis Clínico',
    generateClinicalSummary: 'Generar Resumen',
    executiveSummary: 'Resumen Ejecutivo',
    identifiedPatterns: 'Patrones',
    clinicalRecommendations: 'Recomendaciones',
    newClinic: 'Nueva Unidad',
    yourClinics: 'Sus Unidades',
    createUnit: 'Crear Unidad',
    downloadDataLGPD: 'Descargar mis datos',
    printReport: 'Imprimir Informe',
    exportExcel: 'Exportar Excel',
    resolve: 'Resolver',
    hide: 'Ocultar',
    consent: 'Gestión de Consentimiento',
    patients: 'Pacientes',
    riskLevel: 'Nivel de Riesgo',
    riskLevels: {
      low: 'Estable',
      medium: 'Riesgo Moderado',
      high: 'Alto Risco'
    },
    shared: 'Compartido',
    quickActions: 'Acciones Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Registro por Voz',
    writeDiary: 'Escribir Diario',
    diaryTitle: 'Mi Diario',
    diarySubtitle: 'Un espacio para pensamientos.',
    writeNew: '+ Escribir',
    emptyBook: 'Vacio',
    insights: 'Estadísticas',
    noData: 'Sin datos',
    daily: 'Diario',
    weekly: 'Semanal',
    monthly: 'Mensal',
    moodFlow: 'Flujo',
    energyLevels: 'Niveles',
    recent: 'Reciente',
    days7: '7 Días',
    days30: '30 Días',
    accountSettings: 'Cuenta y Ajustes',
    language: 'Idioma',
    name: 'Nombre',
    email: 'Correo',
    role: 'Perfil',
    signOut: 'Salir',
    deleteAccount: 'Eliminar Cuenta',
    switchRole: 'Cambiar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diario',
    tabVoice: '🎙️ Registro por Voz',
    listening: 'Escuchando...',
    voicePrompt: 'Diario de voz...\nEl sistema procesará su humor.',
    howAreYou: '¿Cómo estás?',
    energy: 'Nivel de Energía',
    tags: 'Etiquetas',
    notesTitle: '📝 Notas',
    diaryPromptTitle: '📖 Querido Diario...',
    placeholderDiary: 'Escribe...',
    placeholderMood: 'Añadir algo?',
    cancel: 'Cancelar',
    save: 'Guardar',
    login: 'Entrar',
    createAccount: 'Crear Cuenta',
    backToLogin: 'Volver',
    orEmail: 'Correo',
    standardUser: 'Estándar',
    patientMode: 'Paciente',
    professional: 'Profesional',
    stdDesc: 'Diario personal.',
    patDesc: 'Compartir con médico.',
    docDesc: 'Para médicos.',
    back: 'Volver',
    docPortal: 'Portal Médico',
    yourPatients: 'Tus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Correo del paciente',
    connect: 'Conectar',
    noPatients: 'Sin pacientes.',
    selectPatient: 'Seleccionar paciente.',
    clinicalNotes: 'Notas Clínicas',
    addNote: 'Añadir Nota',
    saveNote: 'Guardar Nota',
    patientNotFound: 'No encontrado.',
    alreadyConnected: 'Ya conectado.',
    visibleEntries: 'Entradas Visibles',
    avgMood: 'Promedio Humor',
    avgEnergy: 'Promedio Energía',
    moodProgression: 'Evolución',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensaje',
    sharedWithPatient: 'Compartido',
    doctorMessage: 'Mensaje del Médico',
    micOn: 'Escuchando...',
    micOff: 'Grabar',
    selectDate: 'Fecha',
    selectMonth: 'Mes',
    viewMode: 'Modo',
    viewDay: 'Día',
    viewMonth: 'Mes',
    reply: 'Responder',
    writeReply: 'Escribir...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuario Común.',
    upgradeToPatient: 'Activar Paciente',
    upgradeSuccess: 'Actualizado.',
    recentNotifications: 'Notificaciones',
    sentReply: 'respondió',
    viewConversation: 'Ver',
    deleteConfirm: '¿Seguro?',
    confirmDisconnect: '¿Está seguro de que desea revocar el acceso de este profesional?',
    disconnectSuccess: 'Acceso revocado con éxito.',
    summaryResult: 'Resumen Clínico',
    summaryError: 'Error al generar el resumen. Inténtelo de nuevo.',
    consentManagement: 'Gestión de Consentimiento',
    moodEvolution: 'Evolución del Humor',
    riskScore: 'Puntuación de Estabilidad',
    requestAnalysis: 'Solicitar Análisis de Evolución',
    evolutionSummary: 'Resumen de Evolución',
    pointsOfAttention: 'Puntos de Atención',
    periodAnalysis: 'Situación del Período'
  },
  fr: {
    home: 'Accueil',
    diary: 'Journal',
    stats: 'Graphiques',
    settings: 'Réglages',
    hello: 'Bonjour,',
    readyTrack: 'Prêt ?',
    clinicalSecurity: 'Sécurité clinique',
    noEntries: 'Aucun record',
    waitingStory: 'Attente...',
    startNow: 'Commencer',
    lastMood: 'Humeur',
    entries: 'Entrées',
    connectedDoctors: 'Médecins',
    recentActivity: 'Activité',
    securityTransparency: 'Transparence',
    dataAccessHistory: 'Historique',
    accessedBy: 'Accédé par',
    at: 'à',
    clinicalInsights: 'Analyses Cliniques',
    generateClinicalSummary: 'Générer Résumé',
    executiveSummary: 'Résumé',
    identifiedPatterns: 'Modèles',
    clinicalRecommendations: 'Recommandations',
    newClinic: 'Nouvelle Unité',
    yourClinics: 'Vos Unités',
    createUnit: 'Créer Unité',
    downloadDataLGPD: 'Télécharger',
    printReport: 'Imprimer',
    exportExcel: 'Exporter Excel',
    resolve: 'Résoudre',
    hide: 'Masquer',
    consent: 'Consentement',
    patients: 'Patients',
    riskLevel: 'Risque',
    riskLevels: {
      low: 'Stable',
      medium: 'Moyen',
      high: 'Élevé'
    },
    shared: 'Partagé',
    quickActions: 'Actions',
    logMood: 'Humeur',
    voiceLog: 'Audio',
    writeDiary: 'Écrire',
    diaryTitle: 'Journal',
    diarySubtitle: 'Espace privé.',
    writeNew: '+ Écrire',
    emptyBook: 'Vide',
    insights: 'Stats',
    noData: 'Pas de données',
    daily: 'Journalier',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    moodFlow: 'Flux',
    energyLevels: 'Niveaux',
    recent: 'Récent',
    days7: '7 Jours',
    days30: '30 Jours',
    accountSettings: 'Compte',
    language: 'Langue',
    name: 'Nom',
    email: 'E-mail',
    role: 'Profil',
    signOut: 'Déconnexion',
    deleteAccount: 'Supprimer',
    switchRole: 'Changer Profil',
    tabMood: '📊 Humeur',
    tabDiary: '📖 Journal',
    tabVoice: '🎙️ Enregistrement Vocal',
    listening: 'Écoute...',
    voicePrompt: 'Journal vocal...\nLe système traitera votre humeur.',
    howAreYou: 'Comment ça va ?',
    energy: 'Énergie',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Cher Journal...',
    placeholderDiary: 'Écrire...',
    placeholderMood: 'Ajouter ?',
    cancel: 'Annuler',
    save: 'Enregistrer',
    login: 'Connexion',
    createAccount: 'Créer',
    backToLogin: 'Retour',
    orEmail: 'Email',
    standardUser: 'Standard',
    patientMode: 'Patient',
    professional: 'Professionnel',
    stdDesc: 'Journal privé.',
    patDesc: 'Partager.',
    docDesc: 'Pour médecins.',
    back: 'Retour',
    docPortal: 'Portail Docteur',
    yourPatients: 'Vos Patients',
    connectPatient: 'Connecter Patient',
    enterPatientEmail: 'Email patient',
    connect: 'Connecter',
    noPatients: 'Aucun.',
    selectPatient: 'Sélectionner.',
    clinicalNotes: 'Notes Cliniques',
    addNote: 'Ajouter',
    saveNote: 'Enregistrer',
    patientNotFound: 'Non trouvé.',
    alreadyConnected: 'Déjà connecté.',
    visibleEntries: 'Entrées Visibles',
    avgMood: 'Moyenne Humeur',
    avgEnergy: 'Moyenne Énergie',
    moodProgression: 'Évolution',
    privateNotes: 'Notes Privées',
    sharedNotes: 'Message',
    sharedWithPatient: 'Partagé',
    doctorMessage: 'Message Docteur',
    micOn: 'Écoute...',
    micOff: 'Enregistrer',
    selectDate: 'Date',
    selectMonth: 'Mois',
    viewMode: 'Mode',
    viewDay: 'Jour',
    viewMonth: 'Mois',
    reply: 'Répondre',
    writeReply: 'Écrire...',
    sendReply: 'Envoyer',
    userIsStandard: 'Utilisateur Commun.',
    upgradeToPatient: 'Activer Pacient',
    upgradeSuccess: 'Actualisé.',
    recentNotifications: 'Notifications',
    sentReply: 'a répondu',
    viewConversation: 'Voir',
    deleteConfirm: 'Sûr ?',
    confirmDisconnect: 'Êtes-vous sûr de vouloir révoquer l\'accès de ce professionnel ?',
    disconnectSuccess: 'Accès révoqué avec succès.',
    summaryResult: 'Résumé Clinique',
    summaryError: 'Échec de la génération du résumé. Veuillez réessayer.',
    consentManagement: 'Gestion du Consentement',
    moodEvolution: 'Évolution de l\'Humeur',
    riskScore: 'Score de Stabilité',
    requestAnalysis: 'Demander une Analyse d\'Évolution',
    evolutionSummary: 'Résumé de l\'Évolution',
    pointsOfAttention: 'Points d\'Attention',
    periodAnalysis: 'Situation de la Période'
  },
  de: { // German
    home: 'Startseite',
    diary: 'Tagebuch',
    stats: 'Statistiken',
    settings: 'Einstellungen',
    hello: 'Hallo,',
    readyTrack: 'Bereit, deinen Tag festzuhalten?',
    clinicalSecurity: 'Deine emotionale Reise mit klinischer Sicherheit',
    noEntries: 'Noch keine Einträge',
    waitingStory: 'Dein Tagebuch wartet auf deine erste Geschichte.',
    startNow: 'Jetzt starten',
    lastMood: 'Letzte Stimmung',
    entries: 'Einträge',
    connectedDoctors: 'Verbundene Ärzte',
    recentActivity: 'Letzte Aktivität',
    securityTransparency: 'Sicherheit & Transparenz',
    dataAccessHistory: 'Datenzugriffsverlauf',
    accessedBy: 'Zugriff durch',
    at: 'am',
    clinicalInsights: 'Klinische Erkenntnisse',
    generateClinicalSummary: 'Klinische Zusammenfassung erstellen',
    executiveSummary: 'Zusammenfassung',
    identifiedPatterns: 'Identifizierte Muster',
    clinicalRecommendations: 'Klinische Empfehlungen',
    newClinic: 'Neue Einheit / Klinik',
    yourClinics: 'Deine Einheiten',
    createUnit: 'Einheit erstellen',
    downloadDataLGPD: 'Meine Daten herunterladen',
    printReport: 'Bericht drucken',
    exportExcel: 'Excel exportieren',
    resolve: 'Lösen',
    hide: 'Verbergen',
    consent: 'Zustimmungsverwaltung',
    patients: 'Patienten',
    riskLevel: 'Risikostufe',
    riskLevels: {
      low: 'Stable',
      medium: 'Mittleres Risiko',
      high: 'Hohes Risiko'
    },
    shared: 'Geteilt',
    quickActions: 'Schnellaktionen',
    logMood: 'Stimmung',
    voiceLog: 'Sprachaufnahme',
    writeDiary: 'Tagebuch schreiben',
    diaryTitle: 'Mein Tagebuch',
    diarySubtitle: 'Ein Raum für deine Gedanken.',
    writeNew: '+ Neu schreiben',
    emptyBook: 'Dein Buch ist leer.',
    insights: 'Einblicke',
    noData: 'Noch keine Daten.',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    moodFlow: 'Stimmungsverlauf',
    energyLevels: 'Energielevel',
    recent: 'Kürzlich',
    days7: '7 Tage',
    days30: '30 Tage',
    accountSettings: 'Konto & Einstellungen',
    language: 'Sprache',
    name: 'Name',
    email: 'E-Mail',
    role: 'Rolle',
    signOut: 'Abmelden',
    deleteAccount: 'Konto löschen',
    switchRole: 'Rolle wechseln',
    tabMood: '📊 Stimmung',
    tabDiary: '📖 Tagebuch',
    tabVoice: '🎙️ Sprachaufnahme',
    listening: 'Ich höre zu...',
    voicePrompt: 'Erzähl mir von deinem Tag...\nDas System wird Ihre Stimmung verarbeiten.',
    howAreYou: 'Wie fühlst du dich?',
    energy: 'Energielevel',
    tags: 'Tags',
    notesTitle: '📝 Notizen',
    diaryPromptTitle: '📖 Liebes Tagebuch...',
    placeholderDiary: 'Schreibe etwas...',
    placeholderMood: 'Etwas hinzufügen?',
    cancel: 'Abbrechen',
    save: 'Speichern',
    login: 'Anmelden',
    createAccount: 'Konto erstellen',
    backToLogin: 'Zurück zum Login',
    orEmail: 'Oder per E-Mail',
    standardUser: 'Standardnutzer',
    patientMode: 'Patient',
    professional: 'Profi',
    stdDesc: 'Persönliches Tagebuch.',
    patDesc: 'Mit Therapeut teilen.',
    docDesc: 'Für Therapeuten.',
    back: 'Zurück',
    docPortal: 'Ärzteportal',
    yourPatients: 'Deine Patienten',
    connectPatient: 'Patient verbinden',
    enterPatientEmail: 'Patienten-E-Mail eingeben',
    connect: 'Verbinden',
    noPatients: 'Keine Patienten.',
    selectPatient: 'Patient auswählen.',
    clinicalNotes: 'Klinische Notizen',
    addNote: 'Notiz hinzufügen',
    saveNote: 'Notiz speichern',
    patientNotFound: 'Patient nicht gefunden.',
    alreadyConnected: 'Bereits verbunden.',
    visibleEntries: 'Sichtbare Einträge',
    avgMood: 'Durchschnitt Stimmung',
    avgEnergy: 'Durchschnitt Energie',
    moodProgression: 'Verlauf',
    privateNotes: 'Private Notizen',
    sharedNotes: 'Nachricht',
    sharedWithPatient: 'Mit Patient geteilt',
    doctorMessage: 'Nachricht vom Arzt',
    micOn: 'Höre zu...',
    micOff: 'Aufnahme beenden',
    selectDate: 'Datum',
    selectMonth: 'Monat',
    viewMode: 'Ansicht',
    viewDay: 'Tag',
    viewMonth: 'Monat',
    reply: 'Antworten',
    writeReply: 'Antwort schreiben...',
    sendReply: 'Senden',
    userIsStandard: 'Standardbenutzer.',
    upgradeToPatient: 'Patientenmodus aktivieren',
    upgradeSuccess: 'Aktualisiert.',
    recentNotifications: 'Benachrichtigungen',
    sentReply: 'hat geantwortet',
    viewConversation: 'Ansehen',
    deleteConfirm: 'Sicher?',
    confirmDisconnect: 'Zugriff widerrufen?',
    disconnectSuccess: 'Erfolgreich widerrufen.',
    summaryResult: 'Klinische Zusammenfassung',
    summaryError: 'Zusammenfassung konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',
    consentManagement: 'Zustimmungsverwaltung',
    moodEvolution: 'Stimmungsentwicklung',
    riskScore: 'Stabilitätswert',
    requestAnalysis: 'Analyse anfordern',
    evolutionSummary: 'Zusammenfassung',
    pointsOfAttention: 'Achtungspunkte',
    periodAnalysis: 'Periodenanalyse'
  },
  ja: { // Japanese
    home: 'ホーム',
    diary: '日記',
    stats: '統計',
    settings: '設定',
    hello: 'こんにちは、',
    readyTrack: '今日の旅を記録しますか？',
    clinicalSecurity: '臨床的なセキュリティで守られた感情の旅',
    noEntries: 'エントリーなし',
    waitingStory: 'あなたの日記が待っています。',
    startNow: '今すぐ開始',
    lastMood: '最後の気分',
    entries: 'エントリー',
    connectedDoctors: '連携医師',
    recentActivity: '最近のアクティビティ',
    securityTransparency: 'セキュリティと透明性',
    dataAccessHistory: 'データアクセス履歴',
    accessedBy: 'アクセス者',
    at: '日時',
    clinicalInsights: '臨床インサイト',
    generateClinicalSummary: '臨床サマリー生成',
    executiveSummary: '要約',
    identifiedPatterns: '特定されたパターン',
    clinicalRecommendations: '臨床的推奨',
    newClinic: '新しいユニット/クリニック',
    yourClinics: 'あなたのユニット',
    createUnit: 'ユニット作成',
    downloadDataLGPD: 'データダウンロード',
    printReport: 'レポート印刷',
    exportExcel: 'Excel出力',
    resolve: '解決',
    hide: '隠す',
    consent: '同意管理',
    patients: '患者',
    riskLevel: 'リスクレベル',
    riskLevels: {
      low: '安定',
      medium: '中程度',
      high: '高リスク'
    },
    shared: '共有',
    quickActions: 'クイックアクション',
    logMood: '気分を記録',
    voiceLog: '音声記録',
    writeDiary: '日記を書く',
    diaryTitle: '私の日記',
    diarySubtitle: 'あなたの考えや物語のための場所。',
    writeNew: '+ 新規作成',
    emptyBook: '本は空です。',
    insights: 'インサイト',
    noData: 'データなし。',
    daily: '毎日',
    weekly: '毎週',
    monthly: '毎月',
    moodFlow: '気分の流れ',
    energyLevels: 'エネルギーレベル',
    recent: '最近',
    days7: '7日間',
    days30: '30日間',
    accountSettings: 'アカウント設定',
    language: '言語',
    name: '名前',
    email: 'メール',
    role: '役割',
    signOut: 'ログアウト',
    deleteAccount: 'アカウント削除',
    switchRole: '役割切替',
    tabMood: '📊 気分',
    tabDiary: '📖 日記',
    tabVoice: '🎙️ 音声記録',
    listening: '聞いています...',
    voicePrompt: '今日のことや気分を話してください...\nシステムが感情を処理します。',
    howAreYou: 'ご機嫌いかがですか？',
    energy: 'エネルギー',
    tags: 'タグ',
    notesTitle: '📝 メモ',
    diaryPromptTitle: '📖 親愛なる日記へ...',
    placeholderDiary: '書き始める...',
    placeholderMood: '追加しますか？',
    cancel: 'キャンセル',
    save: '保存',
    login: 'ログイン',
    createAccount: 'アカウント作成',
    backToLogin: 'ログインへ戻る',
    orEmail: 'またはメールで',
    standardUser: '標準ユーザー',
    patientMode: '患者',
    professional: '専門家',
    stdDesc: '個人的な日記。',
    patDesc: 'セラピストと共有。',
    docDesc: 'セラピスト用。',
    back: '戻る',
    docPortal: '医師ポータル',
    yourPatients: '担当患者',
    connectPatient: '患者を接続',
    enterPatientEmail: '患者のメールを入力',
    connect: '接続',
    noPatients: '患者がいません。',
    selectPatient: '患者を選択してください。',
    clinicalNotes: '臨床メモ',
    addNote: 'メモ追加',
    saveNote: 'メモ保存',
    patientNotFound: '患者が見つかりません。',
    alreadyConnected: '既に接続されています。',
    visibleEntries: '表示可能なエントリー',
    avgMood: '平均気分',
    avgEnergy: '平均エネルギー',
    moodProgression: '気分の推移',
    privateNotes: '非公開メモ',
    sharedNotes: '患者へのメッセージ',
    sharedWithPatient: '患者と共有',
    doctorMessage: '医師からのメッセージ',
    micOn: '聞いています...',
    micOff: '録音停止',
    selectDate: '日付選択',
    selectMonth: '月選択',
    viewMode: '表示モード',
    viewDay: '日',
    viewMonth: '月',
    reply: '返信',
    writeReply: '返信を書く...',
    sendReply: '送信',
    userIsStandard: '標準ユーザーです。',
    upgradeToPatient: '患者モード有効化',
    upgradeSuccess: 'アップグレード完了。',
    recentNotifications: '最近の通知',
    sentReply: '返信しました',
    viewConversation: '会話を見る',
    deleteConfirm: '本当によろしいですか？',
    confirmDisconnect: 'アクセス権を取り消しますか？',
    disconnectSuccess: 'アクセスを正常に取り消しました。',
    summaryResult: '臨床サマリー',
    summaryError: 'サマリーの生成に失敗しました。もう一度お試しください。',
    consentManagement: '同意管理',
    moodEvolution: '気分の進化',
    riskScore: '安定性スコア',
    requestAnalysis: '分析リクエスト',
    evolutionSummary: '進化サマリー',
    pointsOfAttention: '注意点',
    periodAnalysis: '期間分析'
  },
  zh: { // Chinese (Simplified)
    home: '首页',
    diary: '日记',
    stats: '统计',
    settings: '设置',
    hello: '你好，',
    readyTrack: '准备好记录今天了吗？',
    clinicalSecurity: '具有临床安全性的情感旅程',
    noEntries: '暂无记录',
    waitingStory: '你的日记正在等待第一个故事。',
    startNow: '现在开始',
    lastMood: '最新心情',
    entries: '条目',
    connectedDoctors: '关联医生',
    recentActivity: '最近活动',
    securityTransparency: '安全与透明',
    dataAccessHistory: '数据访问历史',
    accessedBy: '访问者',
    at: '时间',
    clinicalInsights: '临床洞察',
    generateClinicalSummary: '生成临床摘要',
    executiveSummary: '执行摘要',
    identifiedPatterns: '识别模式',
    clinicalRecommendations: '临床建议',
    newClinic: '新建诊所',
    yourClinics: '你的诊所',
    createUnit: '创建',
    downloadDataLGPD: '下载数据',
    printReport: '打印报告',
    exportExcel: '导出Excel',
    resolve: '解决',
    hide: '隐藏',
    consent: '同意管理',
    patients: '患者',
    riskLevel: '风险等级',
    riskLevels: {
      low: '稳定',
      medium: '中等风险',
      high: '高风险'
    },
    shared: '已共享',
    quickActions: '快捷操作',
    logMood: '记录心情',
    voiceLog: '语音记录',
    writeDiary: '写日记',
    diaryTitle: '我的日记',
    diarySubtitle: '记录思想的空间。',
    writeNew: '+ 新建',
    emptyBook: '空空如也。',
    insights: '洞察',
    noData: '暂无数据。',
    daily: '每日',
    weekly: '每周',
    monthly: '每月',
    moodFlow: '心情流',
    energyLevels: '能量水平',
    recent: '最近',
    days7: '7天',
    days30: '30天',
    accountSettings: '账户设置',
    language: '语言',
    name: '姓名',
    email: '邮箱',
    role: '角色',
    signOut: '退出',
    deleteAccount: '删除账户',
    switchRole: '切换角色',
    tabMood: '📊 心情',
    tabDiary: '📖 日记',
    tabVoice: '🎙️ 语音记录',
    listening: '正在聆听...',
    voicePrompt: '告诉我你的一天...\n系统将处理您的情绪。',
    howAreYou: '你感觉如何？',
    energy: '能量',
    tags: '标签',
    notesTitle: '📝 笔记',
    diaryPromptTitle: '📖 亲爱的日记...',
    placeholderDiary: '开始写作...',
    placeholderMood: '补充？',
    cancel: '取消',
    save: '保存',
    login: '登录',
    createAccount: '创建账户',
    backToLogin: '返回登录',
    orEmail: '或使用邮箱',
    standardUser: '标准用户',
    patientMode: '患者',
    professional: '专业人士',
    stdDesc: '个人日记。',
    patDesc: '与治疗师共享。',
    docDesc: '供医生查看。',
    back: '返回',
    docPortal: '医生门户',
    yourPatients: '你的患者',
    connectPatient: '连接患者',
    enterPatientEmail: '输入患者邮箱',
    connect: '连接',
    noPatients: '无患者。',
    selectPatient: '选择患者。',
    clinicalNotes: '临床笔记',
    addNote: '添加笔记',
    saveNote: '保存笔记',
    patientNotFound: '未找到患者。',
    alreadyConnected: '已连接。',
    visibleEntries: '可见条目',
    avgMood: '平均心情',
    avgEnergy: '平均能量',
    moodProgression: '心情趋势',
    privateNotes: '私人笔记',
    sharedNotes: '消息',
    sharedWithPatient: '与患者共享',
    doctorMessage: '医生留言',
    micOn: '聆听中...',
    micOff: '停止录音',
    selectDate: '选择日期',
    selectMonth: '选择月份',
    viewMode: '视图模式',
    viewDay: '天',
    viewMonth: '月',
    reply: '回复',
    writeReply: '写回复...',
    sendReply: '发送',
    userIsStandard: '标准用户。',
    upgradeToPatient: '升级为患者',
    upgradeSuccess: '升级成功。',
    recentNotifications: '最近通知',
    sentReply: '回复了',
    viewConversation: '查看对话',
    deleteConfirm: '确定吗？',
    confirmDisconnect: '确认断开？',
    disconnectSuccess: '成功取消访问。',
    summaryResult: '临床摘要',
    summaryError: '生成摘要失败。请重试。',
    consentManagement: '同意管理',
    moodEvolution: '情绪演变',
    riskScore: '稳定分',
    requestAnalysis: '请求分析',
    evolutionSummary: '演变摘要',
    pointsOfAttention: '关注点',
    periodAnalysis: '周期分析'
  },
  ar: { // Arabic (RTL support should be handled by CSS if needed, text translated here)
    home: 'الرئيسية',
    diary: 'يومياتي',
    stats: 'إحصائيات',
    settings: 'الإعدادات',
    hello: 'مرحباً،',
    readyTrack: 'جاهز لتسجيل رحلتك اليوم؟',
    clinicalSecurity: 'رحلتك العاطفية بأمان سريري',
    noEntries: 'لا توجد مدخلات',
    waitingStory: 'مذكراتك تنتظر قصتك الأولى.',
    startNow: 'ابدأ الآن',
    lastMood: 'آخر حالة مزاجية',
    entries: 'المدخلات',
    connectedDoctors: 'الأطباء المتصلون',
    recentActivity: 'نشاط حديث',
    securityTransparency: 'الأمان والشفافية',
    dataAccessHistory: 'سجل الوصول للبيانات',
    accessedBy: 'تم الوصول بواسطة',
    at: 'في',
    clinicalInsights: 'البصيرة السريرية',
    generateClinicalSummary: 'توليد ملخص سريري',
    executiveSummary: 'ملخص تنفيذي',
    identifiedPatterns: 'الأنماط المحددة',
    clinicalRecommendations: 'توصيات سريرية',
    newClinic: 'عيادة جديدة',
    yourClinics: 'عياداتك',
    createUnit: 'إنشاء وحدة',
    downloadDataLGPD: 'تحميل بياناتي',
    printReport: 'طباعة التقرير',
    exportExcel: 'تصدير Excel',
    resolve: 'حل',
    hide: 'إخفاء',
    consent: 'إدارة الموافقة',
    patients: 'المرضى',
    riskLevel: 'مستوى الخطر',
    riskLevels: {
      low: 'مستقر',
      medium: 'خطر متوسط',
      high: 'خطر مرتفع'
    },
    shared: 'مشترك',
    quickActions: 'إجراءات سريعة',
    logMood: 'سجل المزاج',
    voiceLog: 'تسجيل صوتي',
    writeDiary: 'اكتب مذكرات',
    diaryTitle: 'يومياتي',
    diarySubtitle: 'مساحة لأفكارك.',
    writeNew: '+ كتابة جديد',
    emptyBook: 'كتابك فارغ.',
    insights: 'رؤى',
    noData: 'لا توجد بيانات.',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    moodFlow: 'تدفق المزاج',
    energyLevels: 'مستويات الطاقة',
    recent: 'مؤخراً',
    days7: '7 أيام',
    days30: '30 يوم',
    accountSettings: 'إعدادات الحساب',
    language: 'اللغة',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    role: 'الدور',
    signOut: 'تسجيل الخروج',
    deleteAccount: 'حذف الحساب',
    switchRole: 'تبديل الدور',
    tabMood: '📊 المزاج',
    tabDiary: '📖 اليوميات',
    tabVoice: '🎙️ تسجيل صوتي',
    listening: 'أستمع...',
    voicePrompt: 'أخبرني عن يومك...\nسيقوم النظام بمعالجة مشاعرك.',
    howAreYou: 'كيف تشعر؟',
    energy: 'الطاقة',
    tags: 'الوسوم',
    notesTitle: '📝 الملاحظات',
    diaryPromptTitle: '📖 عزيزتي اليوميات...',
    placeholderDiary: 'ابدأ الكتابة...',
    placeholderMood: 'شيء آخر؟',
    cancel: 'إلغاء',
    save: 'حفظ',
    login: 'دخول',
    createAccount: 'إنشاء حساب',
    backToLogin: 'عودة للدخول',
    orEmail: 'أو عبر البريد',
    standardUser: 'مستخدم عادي',
    patientMode: 'مريض',
    professional: 'محترف',
    stdDesc: 'يوميات شخصية.',
    patDesc: 'شارك مع المعالج.',
    docDesc: 'للمعالجين.',
    back: 'رجوع',
    docPortal: 'بوابة الطبيب',
    yourPatients: 'مرضاك',
    connectPatient: 'ربط مريض',
    enterPatientEmail: 'أدخل بريد المريض',
    connect: 'ربط',
    noPatients: 'لا يوجد مرضى.',
    selectPatient: 'اختر مريضاً.',
    clinicalNotes: 'ملاحظات سريرية',
    addNote: 'إضافة ملاحظة',
    saveNote: 'حفظ الملاحظة',
    patientNotFound: 'المريض غير موجود.',
    alreadyConnected: 'متصل بالفعل.',
    visibleEntries: 'المدخلات المرئية',
    avgMood: 'متوسط المزاج',
    avgEnergy: 'متوسط الطاقة',
    moodProgression: 'تطور المزاج',
    privateNotes: 'ملاحظات خاصة',
    sharedNotes: 'رسالة',
    sharedWithPatient: 'مشاركة مع المريض',
    doctorMessage: 'رسالة من الطبيب',
    micOn: 'جاري الاستماع...',
    micOff: 'إيقاف التسجيل',
    selectDate: 'اختر التاريخ',
    selectMonth: 'اختر الشهر',
    viewMode: 'وضع العرض',
    viewDay: 'يوم',
    viewMonth: 'شهر',
    reply: 'رد',
    writeReply: 'اكتب رداً...',
    sendReply: 'إرسال',
    userIsStandard: 'مستخدم عادي.',
    upgradeToPatient: 'ترقية لمريض',
    upgradeSuccess: 'تمت الترقية.',
    recentNotifications: 'إشعارات',
    sentReply: 'رد على ملاحظة',
    viewConversation: 'عرض المحادثة',
    deleteConfirm: 'هل أنت متأكد؟',
    confirmDisconnect: 'تأكيد قطع الاتصال؟',
    disconnectSuccess: 'تم إلغاء الوصول بنجاح.',
    summaryResult: 'ملخص سريري',
    summaryError: 'فشل إنشاء الملخص. يرجى المحاولة مرة أخرى.',
    consentManagement: 'إدارة الموافقة',
    moodEvolution: 'تطور الحالة المزاجية',
    riskScore: 'نقاط الاستقرار',
    requestAnalysis: 'طلب تحليل',
    evolutionSummary: 'ملخص التطور',
    pointsOfAttention: 'نقاط الاهتمام',
    periodAnalysis: 'تحليل الفترة'
  }
};