
export const MOODS = [
  { value: 1, label: 'Awful', emoji: '😫', color: 'text-red-500', bg: 'bg-red-500/10', border: 'border-red-500/20' },
  { value: 2, label: 'Bad', emoji: '😔', color: 'text-orange-400', bg: 'bg-orange-500/10', border: 'border-orange-500/20' },
  { value: 3, label: 'Okay', emoji: '😐', color: 'text-gray-400', bg: 'bg-gray-500/10', border: 'border-gray-500/20' },
  { value: 4, label: 'Good', emoji: '🙂', color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
  { value: 5, label: 'Great', emoji: '🤩', color: 'text-purple-400', bg: 'bg-purple-500/10', border: 'border-purple-500/20' },
];

export const ACTIVITIES = [
  'Work', 'Exercise', 'Family', 'Date', 'Gaming', 'Reading', 'Party', 'Relaxing', 'Cleaning'
];

export const SYMPTOMS = [
  'Anxiety', 'Headache', 'Fatigue', 'Insomnia', 'Stress', 'Nausea'
];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    diary: 'My Diary',
    stats: 'Insights',
    settings: 'Settings',
    hello: 'Hello,',
    readyTrack: 'Ready to track your journey today?',
    clinicalSecurity: 'Your emotional journey with clinical security',
    noEntries: 'No entries yet',
    waitingStory: 'Your journal is waiting for your first story.',
    startNow: 'Start Now',
    lastMood: 'Last Mood',
    entries: 'Entries',
    connectedDoctors: 'Connected Doctors',
    recentActivity: 'Recent Activity',
    securityTransparency: 'Security & Transparency',
    dataAccessHistory: 'Data Access History',
    accessedBy: 'Accessed by',
    at: 'at',
    clinicalAiInsights: 'Clinical AI Insights',
    generateClinicalSummary: 'Generate Clinical Summary',
    executiveSummary: 'Executive Summary',
    identifiedPatterns: 'Identified Patterns',
    clinicalRecommendations: 'Clinical Recommendations',
    newClinic: 'New Unit / Clinic',
    yourClinics: 'Your Units',
    createUnit: 'Create Unit',
    downloadDataLGPD: 'Download My Data (GDPR / Portability)',
    printReport: 'Print Clinical Report',
    exportExcel: 'Export Excel',
    resolve: 'Resolve',
    hide: 'Hide',
    consent: 'Consent Management',
    patients: 'Patients',
    riskLevel: 'Risk Level',
    riskLevels: {
      low: 'Stable',
      medium: 'Moderate Risk',
      high: 'High Risk'
    },
    shared: 'Shared',
    quickActions: 'Quick Actions',
    logMood: 'Log Mood',
    voiceLog: 'Voice Log',
    writeDiary: 'Write Diary',
    diaryTitle: 'My Diary',
    diarySubtitle: 'A space for your thoughts and stories.',
    writeNew: '+ Write New',
    emptyBook: 'Your book is empty.',
    insights: 'Insights',
    noData: 'No data available yet. Log your first mood!',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    moodFlow: 'Mood Flow',
    energyLevels: 'Energy Levels',
    recent: 'Recent',
    days7: '7 Days',
    days30: '30 Days',
    accountSettings: 'Account & Settings',
    language: 'Language',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account Permanently',
    switchRole: 'Switch Role',
    tabMood: '📊 Mood',
    tabDiary: '📖 Diary',
    tabVoice: '🎙️ Voice AI',
    listening: 'I am listening...',
    voicePrompt: 'Tell me about your day or how you feel.\nThe AI will detect your mood and write in your diary.',
    howAreYou: 'How are you feeling?',
    energy: 'Energy Level',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Dear Diary...',
    placeholderDiary: 'Start writing or use voice...',
    placeholderMood: 'Anything to add?',
    cancel: 'Cancel',
    save: 'Save Entry',
    login: 'Login',
    createAccount: 'Create Account',
    backToLogin: 'Back to Login',
    orEmail: 'Or via email',
    standardUser: 'Standard User',
    patientMode: 'Patient',
    professional: 'Professional',
    stdDesc: 'Personal journaling. Private analytics.',
    patDesc: 'Share specific logs with your therapist.',
    docDesc: 'For therapists to view patient data.',
    back: 'Back',
    docPortal: 'Therapist Portal',
    yourPatients: 'Your Patients',
    connectPatient: 'Connect Patient',
    enterPatientEmail: 'Enter patient email',
    connect: 'Connect',
    noPatients: 'No patients connected.',
    selectPatient: 'Select a patient to view records.',
    clinicalNotes: 'Clinical Observations',
    addNote: 'Add Note',
    saveNote: 'Save Note',
    patientNotFound: 'Patient not found. Created a demo patient.',
    alreadyConnected: 'Patient already in your list.',
    visibleEntries: 'Visible Entries',
    avgMood: 'Avg Mood',
    avgEnergy: 'Avg Energy',
    moodProgression: 'Mood Progression',
    privateNotes: 'Private Notes',
    sharedNotes: 'Message to Patient',
    sharedWithPatient: 'Shared with Patient',
    doctorMessage: 'Message from your Doctor',
    micOn: 'Listening...',
    micOff: 'Record Voice Note',
    selectDate: 'Select Date',
    selectMonth: 'Select Month',
    viewMode: 'View Mode',
    viewDay: 'Day',
    viewMonth: 'Month',
    reply: 'Reply',
    writeReply: 'Write a reply...',
    sendReply: 'Send',
    userIsStandard: 'User found, but they are a Standard User. They must upgrade to Patient Mode in their settings.',
    upgradeToPatient: 'Enable Patient Features (Connect with Doctor)',
    upgradeSuccess: 'Account upgraded to Patient Mode. You can now connect with a doctor.',
    recentNotifications: 'Recent Notifications',
    sentReply: 'replied to a note',
    viewConversation: 'View Conversation',
    deleteConfirm: 'Are you sure? This cannot be undone.',
    confirmDisconnect: 'Are you sure you want to revoke this professional\'s access?',
    disconnectSuccess: 'Access revoked successfully.',
    consentManagement: 'Consent Management'
  },
  pt: {
    home: 'Início',
    diary: 'Diário',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Olá,',
    readyTrack: 'Pronto para registrar sua jornada hoje?',
    clinicalSecurity: 'Sua jornada emocional com segurança clínica',
    noEntries: 'Nenhum registro ainda',
    waitingStory: 'Seu diário está esperando sua primeira história.',
    startNow: 'Começar Agora',
    lastMood: 'Último Humor',
    entries: 'Registros',
    connectedDoctors: 'Médicos Conectados',
    recentActivity: 'Atividade Recente',
    securityTransparency: 'Segurança & Transparência',
    dataAccessHistory: 'Histórico de Acesso aos Dados',
    accessedBy: 'Acessado por',
    at: 'em',
    clinicalAiInsights: 'Clinical AI Insights',
    generateClinicalSummary: 'Gerar Sumário Clínico',
    executiveSummary: 'Resumo Executivo',
    identifiedPatterns: 'Padrões Identificados',
    clinicalRecommendations: 'Recomendações Clínicas',
    newClinic: 'Nova Unidade / Clínica',
    yourClinics: 'Suas Unidades',
    createUnit: 'Criar Unidade',
    downloadDataLGPD: 'Baixar meus dados (LGPD / Portabilidade)',
    printReport: 'Imprimir Relatório Clínico',
    exportExcel: 'Exportar Excel',
    resolve: 'Resolver',
    hide: 'Ocultar',
    consent: 'Gestão de Consentimento',
    patients: 'Pacientes',
    riskLevel: 'Nível de Risco',
    riskLevels: {
      low: 'Estável',
      medium: 'Risco Moderado',
      high: 'Alto Risco'
    },
    private: 'Privado',
    shared: 'Compartilhado',
    quickActions: 'Ações Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Voz',
    writeDiary: 'Escrever Diário',
    diaryTitle: 'Meu Diário',
    diarySubtitle: 'Um espaço para seus pensamentos e histórias.',
    writeNew: '+ Escrever',
    emptyBook: 'Seu livro está vazio.',
    insights: 'Estatísticas',
    noData: 'Sem dados ainda. Registre seu primeiro humor!',
    daily: 'Diário',
    weekly: 'Semanal',
    monthly: 'Mensal',
    moodFlow: 'Fluxo de Humor',
    energyLevels: 'Níveis de Energia',
    recent: 'Recente',
    days7: '7 Dias',
    days30: '30 Dias',
    accountSettings: 'Conta e Configurações',
    language: 'Idioma',
    name: 'Nome',
    email: 'E-mail',
    role: 'Perfil',
    signOut: 'Sair',
    deleteAccount: 'Excluir Conta Permanentemente',
    switchRole: 'Trocar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diário',
    tabVoice: '🎙️ Voz IA',
    listening: 'Estou ouvindo...',
    voicePrompt: 'Conte sobre seu dia ou como se sente.\nA IA detectará seu humor e escreverá no diário.',
    howAreYou: 'Como você está se sentindo?',
    energy: 'Nível de Energia',
    tags: 'Tags',
    notesTitle: '📝 Notas',
    diaryPromptTitle: 'Querido Diário...',
    placeholderDiary: 'Comece a escrever ou use a voz...',
    placeholderMood: 'Algo a acrescentar?',
    cancel: 'Cancelar',
    save: 'Salvar Registro',
    login: 'Entrar',
    createAccount: 'Criar Conta',
    backToLogin: 'Voltar para Login',
    patientMode: 'Paciente',
    professional: 'Profissional',
    patDesc: 'Compartilhe registros específicos com seu terapeuta.',
    docDesc: 'Para terapeutas visualizarem dados de pacientes.',
    docPortal: 'Portal do Terapeuta',
    yourPatients: 'Seus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Digite o e-mail do paciente',
    connect: 'Conectar',
    noPatients: 'Nenhum paciente conectado.',
    selectPatient: 'Selecione um paciente para ver os registros.',
    clinicalNotes: 'Observações Clínicas',
    addNote: 'Adicionar Nota',
    saveNote: 'Salvar Nota',
    patientNotFound: 'Paciente não encontrado. Criamos um usuário de teste.',
    alreadyConnected: 'Paciente já está na sua lista.',
    visibleEntries: 'Registros Visíveis',
    avgMood: 'Média Humor',
    avgEnergy: 'Média Energia',
    moodProgression: 'Evolução do Humor',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensagem ao Paciente',
    sharedWithPatient: 'Compartilhado com Paciente',
    doctorMessage: 'Mensagem do seu Médico',
    micOn: 'Ouvindo...',
    micOff: 'Gravar Nota de Voz',
    selectDate: 'Selecionar Data',
    selectMonth: 'Selecionar Mês',
    viewMode: 'Modo de Visualização',
    viewDay: 'Dia',
    viewMonth: 'Mês',
    reply: 'Responder',
    writeReply: 'Escreva uma resposta...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuário encontrado, mas é Comum. Ele precisa ativar o modo Paciente nas configurações dele.',
    upgradeToPatient: 'Ativar Modo Paciente (Conectar com Médico)',
    upgradeSuccess: 'Conta atualizada para Paciente. Agora você pode conectar com um médico.',
    recentNotifications: 'Notificações Recentes',
    sentReply: 'respondeu a uma nota',
    viewConversation: 'Ver Conversa',
    deleteConfirm: 'Tem certeza? Isso não pode ser desfeito.',
    confirmDisconnect: 'Tem certeza que deseja revogar o acesso deste profissional?',
    disconnectSuccess: 'Acesso revogado com sucesso.',
    consentManagement: 'Gestão de Consentimento'
  },
  es: {
    home: 'Inicio',
    diary: 'Diario',
    stats: 'Gráficos',
    settings: 'Ajustes',
    hello: 'Hola,',
    readyTrack: '¿Listo para registrar tu día?',
    clinicalSecurity: 'Tu viaje con seguridad clínica',
    noEntries: 'Sin registros aún',
    waitingStory: 'Tu diario espera tu primera historia.',
    startNow: 'Empezar Ahora',
    lastMood: 'Último Humor',
    entries: 'Registros',
    connectedDoctors: 'Médicos Conectados',
    recentActivity: 'Actividad Reciente',
    securityTransparency: 'Seguridad y Transparencia',
    dataAccessHistory: 'Historial de Acceso',
    accessedBy: 'Accedido por',
    at: 'en',
    clinicalAiInsights: 'Clinical AI Insights',
    generateClinicalSummary: 'Generar Resumen',
    executiveSummary: 'Resumen Ejecutivo',
    identifiedPatterns: 'Patrones',
    clinicalRecommendations: 'Recomendaciones',
    newClinic: 'Nueva Unidad',
    yourClinics: 'Sus Unidades',
    createUnit: 'Crear Unidad',
    downloadDataLGPD: 'Descargar mis datos',
    printReport: 'Imprimir Informe',
    exportExcel: 'Exportar Excel',
    resolve: 'Resolver',
    hide: 'Ocultar',
    consent: 'Gestión de Consentimiento',
    patients: 'Pacientes',
    riskLevel: 'Nivel de Riesgo',
    riskLevels: {
      low: 'Estable',
      medium: 'Riesgo Moderado',
      high: 'Alto Riesgo'
    },
    shared: 'Compartido',
    quickActions: 'Acciones Rápidas',
    logMood: 'Registrar Humor',
    voiceLog: 'Voz',
    writeDiary: 'Escribir Diario',
    diaryTitle: 'Mi Diario',
    diarySubtitle: 'Un espacio para pensamientos.',
    writeNew: '+ Escribir',
    emptyBook: 'Vacio',
    insights: 'Estadísticas',
    noData: 'Sin datos',
    daily: 'Diario',
    weekly: 'Semanal',
    monthly: 'Mensual',
    moodFlow: 'Flujo',
    energyLevels: 'Niveles',
    recent: 'Reciente',
    days7: '7 Días',
    days30: '30 Días',
    accountSettings: 'Cuenta y Ajustes',
    language: 'Idioma',
    name: 'Nombre',
    email: 'Correo',
    role: 'Perfil',
    signOut: 'Salir',
    deleteAccount: 'Eliminar Cuenta',
    switchRole: 'Cambiar Perfil',
    tabMood: '📊 Humor',
    tabDiary: '📖 Diario',
    tabVoice: '🎙️ Voz IA',
    listening: 'Escuchando...',
    voicePrompt: 'Diario de voz...',
    howAreYou: '¿Cómo estás?',
    energy: 'Nivel de Energía',
    tags: 'Etiquetas',
    notesTitle: '📝 Notas',
    diaryPromptTitle: '📖 Querido Diario...',
    placeholderDiary: 'Escribe...',
    placeholderMood: 'Añadir algo?',
    cancel: 'Cancelar',
    save: 'Guardar',
    login: 'Entrar',
    createAccount: 'Crear Cuenta',
    backToLogin: 'Volver',
    orEmail: 'Correo',
    standardUser: 'Estándar',
    patientMode: 'Paciente',
    professional: 'Profesional',
    stdDesc: 'Diario personal.',
    patDesc: 'Compartir con médico.',
    docDesc: 'Para médicos.',
    back: 'Volver',
    docPortal: 'Portal Médico',
    yourPatients: 'Tus Pacientes',
    connectPatient: 'Conectar Paciente',
    enterPatientEmail: 'Correo del paciente',
    connect: 'Conectar',
    noPatients: 'Sin pacientes.',
    selectPatient: 'Seleccionar paciente.',
    clinicalNotes: 'Notas Clínicas',
    addNote: 'Añadir Nota',
    saveNote: 'Guardar Nota',
    patientNotFound: 'No encontrado.',
    alreadyConnected: 'Ya conectado.',
    visibleEntries: 'Entradas Visibles',
    avgMood: 'Promedio Humor',
    avgEnergy: 'Promedio Energía',
    moodProgression: 'Evolución',
    privateNotes: 'Notas Privadas',
    sharedNotes: 'Mensaje',
    sharedWithPatient: 'Compartido',
    doctorMessage: 'Mensaje del Médico',
    micOn: 'Escuchando...',
    micOff: 'Grabar',
    selectDate: 'Fecha',
    selectMonth: 'Mes',
    viewMode: 'Modo',
    viewDay: 'Día',
    viewMonth: 'Mes',
    reply: 'Responder',
    writeReply: 'Escribir...',
    sendReply: 'Enviar',
    userIsStandard: 'Usuario Común.',
    upgradeToPatient: 'Activar Paciente',
    upgradeSuccess: 'Actualizado.',
    recentNotifications: 'Notificaciones',
    sentReply: 'respondió',
    viewConversation: 'Ver',
    deleteConfirm: '¿Seguro?',
    confirmDisconnect: '¿Está seguro de que desea revocar el acceso de este profesional?',
    disconnectSuccess: 'Acceso revocado con éxito.',
    consentManagement: 'Gestión de Consentimiento'
  },
  fr: {
    home: 'Accueil',
    diary: 'Journal',
    stats: 'Graphiques',
    settings: 'Réglages',
    hello: 'Bonjour,',
    readyTrack: 'Prêt ?',
    clinicalSecurity: 'Sécurité clinique',
    noEntries: 'Aucun record',
    waitingStory: 'Attente...',
    startNow: 'Commencer',
    lastMood: 'Humeur',
    entries: 'Entrées',
    connectedDoctors: 'Médecins',
    recentActivity: 'Activité',
    securityTransparency: 'Transparence',
    dataAccessHistory: 'Historique',
    accessedBy: 'Accédé par',
    at: 'à',
    clinicalAiInsights: 'Insights IA',
    generateClinicalSummary: 'Générer Résumé',
    executiveSummary: 'Résumé',
    identifiedPatterns: 'Modèles',
    clinicalRecommendations: 'Recommandations',
    newClinic: 'Nouvelle Unité',
    yourClinics: 'Vos Unités',
    createUnit: 'Créer Unité',
    downloadDataLGPD: 'Télécharger',
    printReport: 'Imprimer',
    exportExcel: 'Exporter Excel',
    resolve: 'Résoudre',
    hide: 'Masquer',
    consent: 'Consentement',
    patients: 'Patients',
    riskLevel: 'Risque',
    riskLevels: {
      low: 'Stable',
      medium: 'Moyen',
      high: 'Élevé'
    },
    shared: 'Partagé',
    quickActions: 'Actions',
    logMood: 'Humeur',
    voiceLog: 'Voix',
    writeDiary: 'Écrire',
    diaryTitle: 'Journal',
    diarySubtitle: 'Espace privé.',
    writeNew: '+ Écrire',
    emptyBook: 'Vide',
    insights: 'Stats',
    noData: 'Pas de données',
    daily: 'Journalier',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    moodFlow: 'Flux',
    energyLevels: 'Niveaux',
    recent: 'Récent',
    days7: '7 Jours',
    days30: '30 Jours',
    accountSettings: 'Compte',
    language: 'Langue',
    name: 'Nom',
    email: 'E-mail',
    role: 'Profil',
    signOut: 'Déconnexion',
    deleteAccount: 'Supprimer',
    switchRole: 'Changer Profil',
    tabMood: '📊 Humeur',
    tabDiary: '📖 Journal',
    tabVoice: '🎙️ Voix IA',
    listening: 'Écoute...',
    voicePrompt: 'Journal vocal...',
    howAreYou: 'Comment ça va ?',
    energy: 'Énergie',
    tags: 'Tags',
    notesTitle: '📝 Notes',
    diaryPromptTitle: '📖 Cher Journal...',
    placeholderDiary: 'Écrire...',
    placeholderMood: 'Ajouter ?',
    cancel: 'Annuler',
    save: 'Enregistrer',
    login: 'Connexion',
    createAccount: 'Créer',
    backToLogin: 'Retour',
    orEmail: 'Email',
    standardUser: 'Standard',
    patientMode: 'Patient',
    professional: 'Professionnel',
    stdDesc: 'Journal privé.',
    patDesc: 'Partager.',
    docDesc: 'Pour médecins.',
    back: 'Retour',
    docPortal: 'Portail Docteur',
    yourPatients: 'Vos Patients',
    connectPatient: 'Connecter Patient',
    enterPatientEmail: 'Email patient',
    connect: 'Connecter',
    noPatients: 'Aucun.',
    selectPatient: 'Sélectionner.',
    clinicalNotes: 'Notes Cliniques',
    addNote: 'Ajouter',
    saveNote: 'Enregistrer',
    patientNotFound: 'Non trouvé.',
    alreadyConnected: 'Déjà connecté.',
    visibleEntries: 'Entrées Visibles',
    avgMood: 'Moyenne Humeur',
    avgEnergy: 'Moyenne Énergie',
    moodProgression: 'Évolution',
    privateNotes: 'Notes Privées',
    sharedNotes: 'Message',
    sharedWithPatient: 'Partagé',
    doctorMessage: 'Message Docteur',
    micOn: 'Écoute...',
    micOff: 'Enregistrer',
    selectDate: 'Date',
    selectMonth: 'Mois',
    viewMode: 'Mode',
    viewDay: 'Jour',
    viewMonth: 'Mois',
    reply: 'Répondre',
    writeReply: 'Écrire...',
    sendReply: 'Envoyer',
    userIsStandard: 'Utilisateur Commun.',
    upgradeToPatient: 'Activer Pacient',
    upgradeSuccess: 'Actualisé.',
    recentNotifications: 'Notifications',
    sentReply: 'a répondu',
    viewConversation: 'Voir',
    deleteConfirm: 'Sûr ?',
    confirmDisconnect: 'Êtes-vous sûr de vouloir révoquer l\'accès de ce professionnel ?',
    disconnectSuccess: 'Accès révoqué avec succès.',
    consentManagement: 'Gestion du Consentement'
  }
};