
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Helper to read .env manually
function loadEnv() {
    try {
        const __dirname = path.dirname(fileURLToPath(import.meta.url));
        const envPath = path.resolve(__dirname, '.env');
        const envFile = fs.readFileSync(envPath, 'utf8');
        const envVars = {};
        envFile.split('\n').forEach(line => {
            const [key, value] = line.split('=');
            if (key && value) {
                envVars[key.trim()] = value.trim().replace(/^["']|["']$/g, ''); // Remove quotes
            }
        });
        return envVars;
    } catch (e) {
        console.error("Error reading .env:", e);
        return {};
    }
}

const env = loadEnv();
const supabaseUrl = env.VITE_SUPABASE_URL;
const supabaseKey = env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("Missing Supabase credentials in .env");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function runTest() {
    console.log("Starting Schema Integration Verify (ESM No-Deps)...");

    // 1. Authenticate as Doctor
    const testDoctorEmail = `dr_test_${Date.now()}@test.com`;
    const testPatientEmail = `pat_test_${Date.now()}@test.com`;
    const password = "password123";

    console.log(`\n--- 1. Creating Users '${testDoctorEmail}' and '${testPatientEmail}' ---`);

    // Create Doctor
    const { data: docAuth, error: docError } = await supabase.auth.signUp({
        email: testDoctorEmail,
        password: password,
        options: { data: { full_name: "Dr Test" } }
    });
    if (docError) { console.error("Doc Signup Error:", docError); return; }
    const docId = docAuth.user?.id;
    console.log("Doctor Created:", docId);

    // Update Doctor Role to 'medico'
    await supabase.from('profiles').update({ role: 'medico' }).eq('id', docId);
    console.log("Doctor Role Updated to 'medico'");


    // Create Patient
    const { data: patAuth, error: patError } = await supabase.auth.signUp({
        email: testPatientEmail,
        password: password,
        options: { data: { full_name: "Patient Test" } }
    });
    if (patError) { console.error("Pat Signup Error:", patError); return; }
    const patId = patAuth.user?.id;
    console.log("Patient Created:", patId);

    // Update Patient Role to 'paciente'
    await supabase.from('profiles').update({ role: 'paciente' }).eq('id', patId);
    console.log("Patient Role Updated to 'paciente'");

    // 2. Test Connection (Doctor connects to Patient)
    console.log(`\n--- 2. Testing Patient Connection ---`);

    // Re-login as Doctor to perform doctor actions
    const { error: loginError } = await supabase.auth.signInWithPassword({
        email: testDoctorEmail,
        password: password
    });
    if (loginError) { console.error("Doc Re-login Error:", loginError); return; }
    console.log("Logged in as Doctor.");

    const { error: connectError } = await supabase.from('doctor_patients').insert({
        doctor_id: docId,
        patient_id: patId
    });

    if (connectError) {
        console.error("Connection Failed (Constraint or RLS):", connectError);
    } else {
        console.log("Connection Success! FK Constraints Satisfied.");
    }

    // 3. Test Medical Dashboard View
    console.log(`\n--- 3. Testing Medical Dashboard View ---`);

    const { data: dashboard, error: dashError } = await supabase
        .from('medical_dashboard')
        .select('*')
        .eq('doctor_id', docId);

    if (dashError) {
        console.error("View Fetch Error:", dashError);
    } else {
        console.log("Dashboard View Result:", dashboard);
        if (dashboard.length > 0 && dashboard[0].patient_id === patId) {
            console.log("SUCCESS: Dashboard View correctly reflects the connection.");
        } else {
            // If view is empty, insert a mood entry for patient to ensure they show up in view?
            // View logic might require at least one entry or not.
            console.log("Dashboard fetch success. Row count: " + dashboard.length);
        }
    }
    // 4. Test Charts Table Access
    console.log(`\n--- 4. Testing Charts Table Access ---`);
    const dummyChart = {
        user_id: patId,
        chart_type: 'weekly_mood',
        data: { mock: "data" }
    };
    const { error: chartInsertError } = await supabase.from('charts').insert(dummyChart);

    if (chartInsertError) {
        console.log("Chart Mock Insert Error (Expected if generated by Trigger only):", chartInsertError.message);
    } else {
        console.log("Mock Chart Inserted.");

        const { data: charts, error: chartFetchError } = await supabase
            .from('charts')
            .select('*')
            .eq('user_id', patId);

        if (chartFetchError) {
            console.error("Chart Fetch Error:", chartFetchError);
        } else {
            console.log("Chart Fetch Result:", charts);
        }
    }
}

runTest();
